# Generated by Django 3.1.6 on 2022-01-17 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('checkout_session_id', models.CharField(blank=True, max_length=250)),
                ('checkout_session_status', models.CharField(blank=True, max_length=50)),
                ('payment_intent_id', models.CharField(blank=True, max_length=250)),
                ('payment_intent_status', models.CharField(blank=True, max_length=50)),
                ('charge_id', models.CharField(blank=True, max_length=250)),
                ('charge_status', models.CharField(blank=True, max_length=50)),
                ('customer_email', models.EmailField(max_length=254, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('amount', models.IntegerField(null=True)),
                ('live_mode', models.BooleanField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
