# Generated by Django 3.1.6 on 2022-01-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topup',
            name='customer_email',
        ),
    ]
