# Generated by Django 3.1.6 on 2022-01-16 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_topup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topup',
            name='amount_from_stripe',
        ),
        migrations.RemoveField(
            model_name='topup',
            name='amount_intent_payment',
        ),
        migrations.RemoveField(
            model_name='topup',
            name='date_intent_payment',
        ),
        migrations.RemoveField(
            model_name='topup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='topup',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='topup',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topup',
            name='charge_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topup',
            name='charge_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='topup',
            name='charge_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topup',
            name='checkout_session_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topup',
            name='checkout_session_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='topup',
            name='checkout_session_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topup',
            name='customer_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topup',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='topup',
            name='customer_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='topup',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topup',
            name='live_mode',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topup',
            name='payment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topup',
            name='payment_intent_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topup',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='topup',
            name='payment_intent_status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='currency',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
