# Generated by Django 3.2.12 on 2022-02-11 20:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_remove_topup_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('street_and_number', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=1280)),
                ('postal_code', models.CharField(max_length=5, validators=[payments.models.Address.postal_code_validator])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelManagers(
            name='topup',
            managers=[
                ('payments', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='topup',
            name='amount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='topup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=32)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.address')),
                ('topup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.topup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
