# Generated by Django 3.0.6 on 2021-12-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_topup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topup',
            name='amount_intent_payment',
        ),
        migrations.RemoveField(
            model_name='topup',
            name='payment_status',
        ),
    ]
