# Generated by Django 3.1.7 on 2022-01-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_topup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='payment_status',
            field=models.CharField(choices=[('1', 'new'), ('2', 'pending'), ('3', 'success'), ('4', 'reject')], default='new', max_length=1),
        ),
    ]
