# Generated by Django 3.2.12 on 2022-02-13 12:14

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20220211_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[payments.models.Address.postal_code_validator]),
        ),
    ]
