# Generated by Django 3.2.12 on 2022-02-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20220209_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_and_appartment',
            new_name='street_number',
        ),
    ]
