# Generated by Django 3.2.12 on 2022-02-26 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20220204_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionDateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0)),
                ('is_percent', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('active_dates', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_dates', to='payments.promotiondaterange')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='payments.promotion')),
            ],
        ),
    ]
