# Generated by Django 3.0.6 on 2021-12-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20211205_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup',
            name='amount_intent_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topup',
            name='payment_status',
            field=models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('success', 'success'), ('reject', 'reject')], default='new', max_length=10),
        ),
    ]
