# Generated by Django 3.1.6 on 2022-01-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20220116_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
