# Generated by Django 3.2.12 on 2022-02-19 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_promotion_toupvalueanddiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='toupvalueanddiscount',
            name='promotion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='payments.promotion'),
            preserve_default=False,
        ),
    ]
