# Generated by Django 3.2.12 on 2022-02-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_address_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='no_in_month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
