# Generated by Django 3.2.12 on 2022-02-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_street_and_appartment_address_street_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_number',
            new_name='street_and_number',
        ),
    ]
