# Generated by Django 3.2.12 on 2022-02-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20220206_1136'),
        ('payments', '0005_rename_street_number_address_street_and_number'),
    ]

    operations = [
    ]
