# Generated by Django 3.1.6 on 2022-01-16 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_auto_20220116_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='charge_body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='charge_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='charge_status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='checkout_session_body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='checkout_session_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='checkout_session_status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='currency',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='customer_body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='customer_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='live_mode',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='payment_intent_body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='payment_intent_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='payment_intent_status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
