# Generated by Django 3.2.12 on 2022-02-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_invoice_no_in_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='no_in_month',
            field=models.IntegerField(null=True),
        ),
    ]
