# Generated by Django 3.2.12 on 2022-02-21 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_toupvalueanddiscount_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='is_on',
            new_name='active',
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_percent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ToUpValueAndDiscount',
        ),
        migrations.AddField(
            model_name='price',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='payments.promotion'),
        ),
    ]
