# Generated by Django 3.2.12 on 2022-02-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_invoice_no_in_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=128),
        ),
    ]
