# Generated by Django 3.1.6 on 2022-01-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20220116_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
