# Generated by Django 3.2.12 on 2022-02-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20220221_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='start_date',
        ),
        migrations.CreateModel(
            name='PromotionDateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('promotion', models.ManyToManyField(to='payments.Promotion')),
            ],
        ),
    ]
