# Generated by Django 3.2.12 on 2022-02-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20220221_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='topup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.topup'),
        ),
    ]
