# Generated by Django 3.2.12 on 2022-02-24 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20220223_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='dates',
        ),
        migrations.AddField(
            model_name='promotion',
            name='active_dates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_dates', to='payments.promotiondaterange'),
        ),
    ]
