# Generated by Django 3.1 on 2020-08-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200820_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='price',
            field=models.FloatField(),
            preserve_default=False,
        ),
    ]
