# Generated by Django 3.1 on 2020-08-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_composition_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_addon',
            field=models.BooleanField(default=True),
        ),
    ]
