# Generated by Django 3.1 on 2020-08-29 09:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_dish_dish_addon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chart',
            new_name='Cart',
        ),
    ]
