# Generated by Django 3.1 on 2020-08-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200829_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredient',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
