# Generated by Django 3.1 on 2020-08-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200830_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredient',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
