# Generated by Django 3.1 on 2020-09-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200830_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('ingredient', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
