# Generated by Django 3.1 on 2020-09-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_weekdish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='price',
        ),
    ]
